---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-pv
  namespace: mealie
  labels:
    app: mealie
spec:
  storageClassName: "local-path"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
  nfs:
    server: 10.0.96.14
    path: "/mnt/data/NFS/mealie"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-storage
  namespace: mealie
  annotations:
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mealie-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-storage-new
  namespace: mealie
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi